FROM docker.io/node:alpine
RUN yarn global add --verbose \
	eslint prettier \
	typescript typescript-language-server \
	tailwindcss @tailwindcss/language-server \
	@astrojs/language-server @astrojs/ts-plugin \
	vls \
	vscode-langservers-extracted
