#!/bin/sh

input="$(
	sudo podman run \
		--privileged \
		--interactive \
		--tty \
		--rm \
		--volume /var/swap/swapfile:/swapfile \
		btrfs_map_physical
)"

real_size="$(tr -d '\r' <<< $input | awk '{print $NF}' | sed -n 2p)"
page_size="$(getconf PAGESIZE)"

echo "$((real_size / page_size))"
