#!/bin/sh

uid=$(id -u)

if [ "$uid" -eq 0 ]; then
	target="root"
else
	target="local"
fi

for image in images/"$target"/*; do
	tag="$(basename "$image")"

	echo "####################################################"
	echo "Building image for '$tag'"
	echo "Context: '$image'"
	echo "####################################################"

	podman build --tag "$tag" "$image"
done
