#!/bin/sh

uid=$(id -u)

if [ "$uid" -eq 0 ]; then
	target="root"
else
	target="local"
fi

for img in images/"$target"/*; do
	tag="$(basename "$img")"

	echo "####################################################"
	echo "Target: '$target'"
	echo "Building image for '$tag'"
	echo "Context: '$img'"
	echo "####################################################"

	podman build --tag "$tag" "$img"
done
