#!/bin/sh

feh --bg-scale $(xdg-user-dir PICTURES)/nord_void.png

pkill polybar
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload main &
done

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a \*:fzfmenu state=floating
