#!/bin/sh

. "${XDG_CACHE_HOME}/wal/colors.sh"

# autostart
nvidia-settings --load-config-only
xset s 300 5
xsetroot -cursor_name circle
feh --bg-fill $(xdg-user-dir PICTURES)/linux_gruvbox_light_ultrawide.png

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 X

bspc config border_width         2
bspc config window_gap           32

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config normal_border_color "$color8"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color9"
bspc config presel_feedback_color "$color1"

bspc rule -a \*:xmenu state=floating locked=on
bspc rule -a Zathura state=tiled
bspc rule -a zoom state=floating

# Start essential services.
# TODO: Pick which variables are needed to run the bspwm session.
systemctl --user import-environment; \
	systemctl --user start wm-session.target; \
	systemctl --user start bspwm-session.target
