#!/bin/sh

feh --bg-scale $(xdg-user-dir PICTURES)/nord_void.png

pkill polybar
polybar --reload main &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           32

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a \*:fzfmenu state=floating
