tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP"]
base_dir = "$XDG_CONFIG_HOME"

[targets."bash/bashrc"]
link.base_dir = "$HOME"
link.name = ".bashrc"
tags.all_of = ["bootstrap"]

#############
### AUDIO ###
#############

[targets.pipewire]
tags.all_of = ["audio"]

###############
### DISPLAY ###
###############

[targets.river]
tags.all_of = ["wayland", "river", "display"]

[targets.kanshi]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river", "sway"]

[targets.fnott]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river"]

[targets.dunst]
tags.all_of = ["wayland", "display"]
tags.any_of = ["sway"]

[targets.yambar]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river"]

[targets."xdg/desktop-portal-wlr"]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river", "sway"]
link.name = "xdg-desktop-portal-wlr"

[targets.fontconfig]
tags.all_of = ["display"]
tags.any_of = ["river", "sway"]

#############
### TOOLS ###
#############

[targets.kakoune]
link.name = "kak"
tags.all_of = ["tools"]

[targets.kak-lsp]
tags.all_of = ["tools"]

[targets.foot]
tags.all_of = ["wayland", "tools"]
tags.any_of = ["river", "sway"]

[targets."latex/latexmkrc"]
link.base_dir = "$HOME"
link.name = ".latexmkrc"
tags.all_of = ["tools"]

[targets."cargo/config.toml"]
link.base_dir = "$HOME/.cargo"
tags.all_of = ["cargo", "tools"]

[targets."sqlite/sqliterc"]
link.base_dir = "$HOME"
link.name = ".sqliterc"
tags.all_of = ["tools"]

[targets.containers]
tags.all_of = ["tools"]

[targets.zathura]
tags.all_of = ["tools"]

[targets.git]
tags.all_of = ["tools"]

[targets."zsh/zshenv"]
link.base_dir = "$HOME"
link.name = ".zshenv"
tags.all_of = ["tools"]

[targets."zsh/zshrc"]
link.name = ".zshrc"
link.base_dir = "$ZDOTDIR"
tags.all_of = ["tools"]

[targets."zsh/functions"]
link.base_dir = "$ZDOTDIR"
tags.all_of = ["tools"]

[targets."zsh/zshrc.d"]
link.base_dir = "$ZDOTDIR"
link.name = ".zshrc.d"
tags.all_of = ["tools"]

[targets."zsh/data"]
link.base_dir = "$XDG_DATA_HOME"
link.name = "zsh"
tags.all_of = ["tools"]

############
### MISC ###
############

[targets.waylock]
tags.all_of = ["wayland", "misc"]
tags.any_of = ["river", "sway"]

[targets."xdg/user-dirs.dirs"]
tags.all_of = ["misc"]

[targets.gtk]
link.name = "gtk-3.0"
tags.all_of = ["misc"]

[targets.firejail]
tags.all_of = ["misc"]
