base_dir = "$XDG_DATA_HOME"

[targets."neovim/data/pack"]
link.name = "git"
link.base_dir = "$XDG_DATA_HOME/nvim/site/pack"

[targets."neovim/data/parsers"]
link.base_dir = "$XDG_DATA_HOME/nvim/site"

[targets."neovim/data/rocks"]
link.base_dir = "$XDG_DATA_HOME/nvim/site"

[targets."zsh/data"]
link.name = "zsh"
