base_dir = "/etc/portage"
work_dir = "$PWD/etc/portage"
tags = ["$HOST"]

[targets."egguheddo.conf"]
link.name = "make.conf"
tags.all_of = ["egguheddo"]

[targets.sets]

[targets.patches]

[targets."package.use/main"]
link.base_dir = "/etc/portage/package.use"

[targets."package.accept_keywords/main"]
link.base_dir = "/etc/portage/package.accept_keywords"
