tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP"]
base_dir = "$XDG_BIN_HOME"

[targets."scripts/riverstart"]
tags.all_of = ["wayland", "river"]

[targets."scripts/steamstart"]

[targets."scripts/dmenu"]
