base_dir = "$XDG_BIN_HOME"
work_dir = "$PWD/scripts"
tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP"]

#############
### AUDIO ###
#############

[targets.decvol]
tags.all_of = ["audio"]

[targets.incvol]
tags.all_of = ["audio"]

[targets.mutevol]
tags.all_of = ["audio"]

############
### MISC ###
############

[targets.doasedit]
tags.all_of = ["misc"]

[targets.fuzzy]
tags.all_of = ["misc"]

[targets.printscreen]
tags.all_of = ["misc"]

[targets.printsnip]
tags.all_of = ["misc"]

###############
### DISPLAY ###
###############

[targets.riverinit]
link.name = "river"
tags.all_of = ["wayland", "river", "display"]

#############
### TOOLS ###
#############

[targets.kakenv]
tags.all_of = ["tools"]
link.name = "kak"
