base_dir = "$XDG_BIN_HOME"
work_dir = "$PWD/scripts"
tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP"]

[targets.data]
link.base_dir = "${XDG_DATA_HOME}"
link.name = "scripts"

#############
### AUDIO ###
#############

[targets.decvol]
tags.all_of = ["audio"]

[targets.incvol]
tags.all_of = ["audio"]

[targets.mutevol]
tags.all_of = ["audio"]

[targets.mvsink]
tags.all_of = ["audio"]

############
### MISC ###
############

[targets.align]
tags.all_of = ["misc"]

[targets.sortline]
tags.all_of = ["misc"]

[targets.wrap]
tags.all_of = ["misc"]

[targets.doasedit]
tags.all_of = ["misc"]

[targets.dmenu]
tags.all_of = ["misc"]

[targets.fuzzy]
tags.all_of = ["misc"]

[targets.printscreen]
tags.all_of = ["misc"]

[targets.printsnip]
tags.all_of = ["misc"]

[targets.sysupdate]
tags.all_of = ["misc"]

[targets.instroot]
tags.all_of = ["misc"]

[targets.emoji]
tags.all_of = ["misc"]

###############
### DISPLAY ###
###############

[targets.riverinit]
link.name = "river"
tags.all_of = ["wayland", "river", "display"]

[targets.swaystart]
link.name = "sway"
tags.all_of = ["wayland", "sway", "display"]

[targets.barstatus]
tags.all_of = ["wayland", "sway", "display"]

[targets.virtout]
tags.all_of = ["wayland", "sway", "display"]

#############
### TOOLS ###
#############

[targets.kakenv]
tags.all_of = ["tools"]
link.name = "kak"

[targets.kakeslint]
tags.all_of = ["tools"]

[targets.lspcontainer]
tags.all_of = ["tools"]

[targets.lspcopy]
tags.all_of = ["tools"]
