tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP"]
base_dir = "$XDG_BIN_HOME"
work_dir = "$PWD/scripts"

[targets.riverstart]
tags.all_of = ["wayland", "river"]

[targets.steamstart]

[targets.dmenu]
tags.any_of = ["river"]

[targets.printscreen]
tags.any_of = ["river"]

[targets.printsnip]
tags.any_of = ["river"]

[targets.screenstart]
tags.all_of = ["wayland"]
tags.any_of = ["river"]

[targets.minestart]
