base_dir = "$XDG_BIN_HOME"
work_dir = "$PWD/scripts"
tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP", "$HOST"]

#############
### AUDIO ###
#############

[targets.decvol]
tags.all_of = ["audio"]

[targets.incvol]
tags.all_of = ["audio"]

[targets.mutevol]
tags.all_of = ["audio"]

############
### MISC ###
############

[targets.align]
tags.all_of = ["misc"]

[targets.sortline]
tags.all_of = ["misc"]

[targets.wrap]
tags.all_of = ["misc"]

[targets.doasedit]
tags.all_of = ["misc"]

[targets.dmenu]
tags.all_of = ["misc"]

[targets.fuzzy]
tags.all_of = ["misc"]

[targets.printscreen]
tags.all_of = ["misc"]

[targets.printsnip]
tags.all_of = ["misc"]

[targets.sysupdate]
tags.all_of = ["misc"]
tags.any_of = ["egguheddo"]

[targets.instroot]
tags.all_of = ["misc"]
tags.any_of = ["egguheddo"]

[targets.mntchroot]
tags.all_of = ["misc"]
tags.any_of = ["egguheddo"]

###############
### DISPLAY ###
###############

[targets.riverinit]
link.name = "river"
tags.all_of = ["wayland", "river", "display"]

#############
### TOOLS ###
#############

[targets.kakenv]
tags.all_of = ["tools"]
link.name = "kak"

[targets.lspcontainer]
tags.all_of = ["tools"]
