tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP", "$HOST"]
base_dir = "$XDG_DATA_HOME/service"
work_dir = "$PWD/sv"

###############
### DISPLAY ###
###############

[targets.rivertile]
tags.all_of = ["wayland", "river", "display"]

[targets.fnott]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river"]

[targets.dunst]
tags.all_of = ["wayland", "display"]
tags.any_of = ["sway"]

[targets.wlsunset]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river", "sway"]

[targets.yambar-primary]
tags.all_of = ["wayland", "river", "display"]
tags.any_of = ["egghead", "skypiea"]

[targets.yambar-secondary]
tags.all_of = ["wayland", "river", "display"]
tags.any_of = ["egghead"]

[targets.river-tag-overlay]
tags.all_of = ["wayland", "river", "display"]

[targets.kanshi]
tags.all_of = ["wayland", "display"]
tags.any_of = ["river", "sway"]

#############
### AUDIO ###
#############

[targets.pipewire]
tags.all_of = ["audio"]
tags.any_of = ["river", "sway"]

[targets.pipewire-pulse]
tags.all_of = ["audio"]
tags.any_of = ["river", "sway"]

[targets.wireplumber]
tags.all_of = ["audio"]
tags.any_of = ["river", "sway"]

[targets.wob]
tags.all_of = ["wayland", "audio"]
tags.any_of = ["river", "sway"]

#############
### TOOLS ###
#############

[targets.footserver]
tags.all_of = ["tools"]
