base_dir = "/etc"
work_dir = "$PWD/etc"
tags = ["$HOST"]

[targets."dracut/$HOST.conf"]
link.base_dir = "/etc/dracut.conf.d"
link.name = "host.conf"

[targets."portage/$HOST.conf"]
link.base_dir = "/etc/portage"
link.name = "make.conf"
tags.all_of = ["$HOST"]

[targets."kernel/$HOST.config"]
link.base_dir = "/usr/src/linux"
link.name = ".config"
tags.all_of = ["$HOST"]

# Sets

[targets."portage/sets/admin"]
link.base_dir = "/etc/portage/sets"

[targets."portage/sets/comm"]
link.base_dir = "/etc/portage/sets"
tags.all_of = ["comm"]

[targets."portage/sets/core"]
link.base_dir = "/etc/portage/sets"

[targets."portage/sets/desktop"]
link.base_dir = "/etc/portage/sets"

[targets."portage/sets/gaming"]
link.base_dir = "/etc/portage/sets"
tags.all_of = ["gaming"]

[targets."portage/sets/keyboard"]
link.base_dir = "/etc/portage/sets"
tags.all_of = ["keyboard"]

[targets."portage/sets/misc"]
link.base_dir = "/etc/portage/sets"

[targets."portage/sets/mobile"]
link.base_dir = "/etc/portage/sets"
tags.any_of = ["skypiea"]

[targets."portage/sets/tools"]
link.base_dir = "/etc/portage/sets"

# Patches

[targets."portage/patches"]
link.base_dir = "/etc/portage"

# Packages

[targets."portage/package.use/main"]
link.base_dir = "/etc/portage/package.use"

[targets."portage/package.accept_keywords/main"]
link.base_dir = "/etc/portage/package.accept_keywords"

[targets."portage/package.license/main"]
link.base_dir = "/etc/portage/package.license"

[targets."portage/package.license/mobile"]
link.base_dir = "/etc/portage/package.license"
tags.any_of = ["skypiea"]

[targets."portage/package.mask/main"]
link.base_dir = "/etc/portage/package.mask"

[targets."portage/package.unmask/main"]
link.base_dir = "/etc/portage/package.unmask"

# Repositories

[targets."portage/repos.conf/crossdev.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/gbrlsnchs.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/gentoo.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/guru.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/local.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/steam-overlay.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/wayland-desktop.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]
