base_dir = "/etc"
work_dir = "$PWD/etc"
tags = ["$HOST"]

[targets."dracut.conf"]

[targets."portage/$HOST.conf"]
link.base_dir = "/etc/portage"
link.name = "make.conf"
tags.all_of = ["$HOST"]

[targets."portage/sets"]
link.base_dir = "/etc/portage"

[targets."portage/patches"]
link.base_dir = "/etc/portage"

# Packages

[targets."portage/package.use/main"]
link.base_dir = "/etc/portage/package.use"
tags.all_of = ["packages"]

[targets."portage/package.accept_keywords/main"]
link.base_dir = "/etc/portage/package.accept_keywords"
tags.all_of = ["packages"]

[targets."portage/package.license/main"]
link.base_dir = "/etc/portage/package.license"
tags.all_of = ["packages"]

[targets."portage/package.mask/main"]
link.base_dir = "/etc/portage/package.mask"
tags.all_of = ["packages"]

[targets."portage/package.unmask/main"]
link.base_dir = "/etc/portage/package.unmask"
tags.all_of = ["packages"]

# Repositories

[targets."portage/repos.conf/crossdev.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/gbrlsnchs.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/gentoo.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/guru.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/local.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/steam-overlay.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]

[targets."portage/repos.conf/wayland-desktop.conf"]
link.base_dir = "/etc/portage/repos.conf"
tags.all_of = ["repos"]
