tags = ["$XDG_SESSION_TYPE", "$XDG_CURRENT_DESKTOP"]
base_dir = ""
work_dir = "$XDG_CACHE_HOME/dotfiles/templates"

###############
### DISPLAY ###
###############

[targets."fnott/fnott.ini"]
link.base_dir = "$PWD/fnott"
tags.all_of = ["wayland", "display"]
tags.any_of = ["river"]

[targets."yambar/primary.yml"]
link.base_dir = "$PWD/yambar"
tags.all_of = ["wayland", "display"]
tags.any_of = ["river"]

[targets."yambar/secondary.yml"]
link.base_dir = "$PWD/yambar"
tags.all_of = ["wayland", "display"]
tags.any_of = ["river"]

[targets."river/theme"]
link.base_dir = "$PWD/river/init.d"
tags.all_of = ["wayland", "river", "display"]

#############
### TOOLS ###
#############

[targets."foot/foot.ini"]
link.base_dir = "$PWD/foot"
tags.all_of = ["wayland", "tools"]
tags.any_of = ["river"]

[targets."zsh/colors.zsh"]
link.base_dir = "$ZDOTDIR/.zshrc.d"
link.name = "00-colors.zsh"
tags.all_of = ["tools"]

############
### MISC ###
############

[targets."waylock/waylock.toml"]
tags.all_of = ["wayland", "misc"]
tags.any_of = ["river"]
link.base_dir = "$PWD/waylock"

[targets."gtk/settings.ini"]
tags.all_of = ["misc"]
link.base_dir = "$PWD/gtk"
