#!/bin/sh

dmenu_in=$(mktemp)
dmenu_out=$(mktemp)

cat /dev/stdin > "$dmenu_in"
foot --app-id dmenu --title dmenu sh -c "cat $dmenu_in | fzf > $dmenu_out"
rm "$dmenu_in"
cat "$dmenu_out"
rm "$dmenu_out"
