#!/bin/sh

read -r -d '' config <<'EOF'
Steam: steam
Discord: discord
Firefox: firefox
Foot: footclient
Lutris: lutris
EOF

program="$(echo "$config" | sort | yq 'keys | .[]' | dmenu)"
echo "$config" | yq ."$program" | xargs -I {} riverctl spawn '{}'
