#!/bin/sh

set -e

vars="$(
	yq --raw-output \
		'to_entries | (.[].value | select(. | type != "string")) |= (. | join(",")) | .[] | .key + "=\"" + .value + "\""' \
		.kakenv 2>/dev/null \
	| xargs --delimiter '\n'
)"

if [ ! -z "${vars}" ]; then
	eval "export ${vars}"
fi

args=""
if [ ! -z "${kak_session}" ]; then
	args="-c ${kak_session}"
fi

/usr/bin/kak ${args} $*
