#!/bin/sh

config_arg=""
if [ -f .eslintrc ]; then
	config_arg="--config=.eslintrc"
fi

cat "$2" \
	| ./node_modules/eslint/bin/eslint.js ${config_arg} --format compact --stdin --stdin-filename="$1" \
	| sed -e "s|: line \([0-9]\+\), col \([0-9]\+\), \([a-zA-Z]\+\) -|:\1:\2: \L\3:|g" \
	| head -n -2
