#!/bin/sh

config_dir="${XDG_CONFIG_HOME}/kak-lsp"
cp "${config_dir}/base.toml" .kaklsp

if [ $# -eq 0 ]; then
	echo "Available LSP configurations:"
	ls -1 "${config_dir}" \
		| xargs -I{} basename {} .toml \
		| grep --invert-match base \
		| xargs -I{} printf "  - %s\n" {}
fi

for lang in $@; do
	printf "\n" >> .kaklsp
	cat "${XDG_CONFIG_HOME}/kak-lsp/${lang}.toml" >> .kaklsp
done
