#!/bin/sh

lsp_runtime="${LSP_RUNTIME:-nodejs}"

podman container run \
	--rm \
	--interactive \
	--network none \
	--workdir "$PWD" \
	--volume "$PWD:$PWD:z" \
	--pid host \
	"${lsp_runtime}-container" $@
