#!/bin/bash

data_home="${XDG_DATA_HOME}/dotdata"
esc=$(printf '\033')
wid=$(xdotool getwindowfocus)

while true
do
  hash -r && (
    compgen -c | rg --word-regexp --file "${data_home}/menu_allowlist.txt" \
    ; cat "${data_home}/menu_commands.txt" | sed --regexp-extended "s/(\(.+\)$)/${esc}[33m\1${esc}[0m/g"
  ) \
    | sort --unique --ignore-case \
    | fzf --ansi --reverse --header='Menu commands' \
    | sed -r "s/\(.+\)//g" \
    | xargs x \
    && xdotool windowunmap $wid
done
