#!/bin/sh

pactl set-sink-mute @DEFAULT_SINK@ toggle

vol=0

if pactl get-sink-mute @DEFAULT_SINK@ | grep --quiet no; then
	vol="$(
		pactl get-sink-volume @DEFAULT_SINK@ \
			| head -n 1 \
			| awk '{print substr($5, 1, length($5)-1)}'
	)"
fi

echo "${vol}" > "$XDG_RUNTIME_DIR/wob.sock"
