#!/bin/sh

img_name="$(date +%s).png"

output="$(xdg-user-dir PICTURES)/$img_name"

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	grim -g "$(slurp)" "$output"
else
	maim -s "$output"
fi

if [ "$?" -eq 0 ]; then
	notify-send --expire-time=5000 "Screenshot taken" "$img_name"
fi
