#!/bin/sh

is_paused=$(dunstctl is-paused)

if [ "$is_paused" = "false" ]; then
	dunstify 'Turning notifications OFF!'
	sleep 2;
	dunstctl close
	dunstctl set-paused true
else
	dunstctl set-paused false
	dunstify 'Notifications are now ON again!'
fi;
