#!/bin/sh

get_last_output() {
	swaymsg --type get_outputs | jq --raw-output '.[] | select(.name | startswith("HEADLESS-")) | .name'
}

nop_sigint() {
	echo ""
}

last_output="$(get_last_output)"
case "${last_output}" in
	HEADLESS-*)
		;;
	*)
		swaymsg create_output
		;;
esac

trap nop_sigint INT

virt_output="$(get_last_output)"
wl-mirror "${virt_output}"

swaymsg output "${virt_output}" unplug
