#!/bin/sh

get_last_output() {
	swaymsg --type get_outputs | jq --raw-output "last | .name"
}

last_output="$(get_last_output)"
case "${last_output}" in
	HEADLESS-*)
		;;
	*)
		swaymsg create_output
		;;
esac

virt_output="$(get_last_output)"
wl-mirror "${virt_output}"
