#!/bin/python

import subprocess
import sys

args = sys.argv[1:]

if len(args) == 0:
	sys.exit()

dev_null = subprocess.DEVNULL
p = subprocess.Popen(args, start_new_session=True, stdout=dev_null, stderr=dev_null)
