[language_server.eslint]
filetypes = ["javascript", "typescript"]
roots = [
	".eslintrc.js",
	".eslintrc.cjs",
	".eslintrc.json",
	".eslintrc.yaml",
	".eslintrc.yml",
	"package.json",
]
command = "lspcontainer"
args = ["vscode-eslint-language-server", "--stdio"]
settings_section = "_"

[language_server.eslint.settings._]
codeAction.disableRuleComment = { enable = true, location = "separateLine" }
codeAction.showDocumentation = { enable = true }
codeActionOnSave = { enable = false, mode = "all" }
experimental = { useFlatConfig = false }
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "npm"
problems = { shortenToSingleLine = false }
quiet = false
rulesCustomizations = {}
run = "onType"
useESLintClass = false
validate = "on"
workingDirectory = { mode = "location" }
