[language_server.gopls]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
settings_section = "gopls"

[language_server.gopls.settings.gopls]
semanticTokens = true
# See https://github.com/golang/tools/blob/master/gopls/doc/settings.md
# "build.buildFlags" = []

[language_server.gopls.settings.gopls.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
contantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true
