[language_server.solargraph]
filetypes = ["ruby"]
roots = ["Gemfile"]
command = "env"
args = ["LSP_RUNTIME=ruby", "solargraph", "stdio"]
settings_section = "_"

[language_server.solargraph.settings._]
# See https://github.com/castwide/solargraph/blob/master/lib/solargraph/language_server/host.rb
# diagnostics = false

[language_server.ruby-lsp]
filetypes = ["ruby"]
roots = ["Gemfile"]
command = "env"
args = ["LSP_RUNTIME=ruby", "ruby-lsp"]
settings_section = "_"

[language_server.ruby-lsp.settings._]
experimentalFeaturesEnabled = true
