[language_server.rust-analyzer]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"

[language_server.rust-analyzer.settings.rust-analyzer]
# See https://rust-analyzer.github.io/manual.html#configuration
hoverActions.enable = false # kak-lsp doesn't support this at the moment
# cargo.features = []
