# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_STATE_HOME="$HOME/.local/state"

PATH="$PATH:$XDG_BIN_HOME"

export XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/flatpak/exports/share
export XDG_CONFIG_DIRS=/etc/xdg

export XDG_MUSIC_DIR=$(xdg-user-dir MUSIC)
export XDG_DESKTOP_DIR=$(xdg-user-dir DESKTOP)
export XDG_DOCUMENTS_DIR=$(xdg-user-dir DOCUMENTS)
export XDG_DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)
export XDG_PICTURES_DIR=$(xdg-user-dir PICTURES)
export XDG_TEMPLATES_DIR=$(xdg-user-dir TEMPLATES)
export XDG_VIDEOS_DIR=$(xdg-user-dir VIDEOS)
export XDG_PUBLICSHARE_DIR=$(xdg-user-dir PUBLICSHARE)

alias ls='ls --color=auto'
